# Generated by Django 6.0.6 on 2026-06-20 23:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='submission',
            old_name='iscorrect',
            new_name='is_correct',
        ),
    ]
